=== Rat-OS/RatOS-configuration/boards/board-definition.schema.json
{
	"$schema": "https://json-schema.org/draft-07/schema",
	"$id": "https://os.ratrig.com/board-defintion.schema.json",
	"title": "Control Board",
	"description": "A 3d printer control board",
	"type": "object",
	"properties": {
		"serialPath": {
			"description": "The path for serial communication with this MCU",
			"type": "string"
		},
		"name": {
			"description": "The name of the control board",
			"type": "string"
		},
		"manufacturer": {
			"description": "The name of the manufacturer of this board",
			"type": "string"
		},
		"firmwareBinaryName": {
			"description": "The firmware binary filename in RatOS",
			"type": "string"
		},
		"compileScript": {
			"description": "The path to the compilation script if the board supports automatic firmware compilation, relative to the board definition directory",
			"type": "string"
		},
		"flashScript": {
			"description": "The path to the flashing script if the board supports automatic firmware flashing, relative to the board definition directory",
			"type": "string"
		},
		"flashInstructions": {
			"description": "Instructions for how to make sure the board can be automatically flashed",
			"type": "string"
		},
		"documentationLink": {
			"description": "Link to the RatOS configuration for this board",
			"type": "string"
		},
		"dfu": {
			"description": "DFU Flashing details",
			"type": "object",
			"properties": {
				"boot0Image": {
					"description": "Path to a picture for locating the boot0 jumper",
					"type": "string"
				},
				"resetImage": {
					"description": "Path to a picture for locating the reset button",
					"type": "string"
				},
				"flashDevice": {
					"description": "A string containing the vendor and device id to use as the flash target, eg 0483:df11",
					"type": "string"
				}
			},
			"required": ["boot0Image", "resetImage", "flashDevice"]
		},
		"sdFileName": {
			"description": "The filename for the firmware binary when flashing via SD card",
			"type": "string"
		}
	},
	"required": ["serialPath", "name", "manufacturer", "firmwareBinaryName", "compileScript", "documentationLink"]
}

=== Rat-OS/RatOS-configuration/boards/btt-manta-m4p-22/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"name": "Manta M4P v2.2",
	"manufacturer": "BIGTREETECH",
	"serialPath": "/dev/btt-manta-m4p-22",
	"firmwareBinaryName": "firmware-btt-manta-m4p-22.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"flashInstructions": "Flashing only works if the SD card slot on the Manta is empty.",
	"documentationLink": "https://os.ratrig.com/docs/boards/btt/manta-m4p"
}

=== Rat-OS/RatOS-configuration/boards/btt-manta-m5p/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"name": "Manta M5P",
	"manufacturer": "BIGTREETECH",
	"serialPath": "/dev/btt-manta-m5p",
	"firmwareBinaryName": "firmware-btt-manta-m5p.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"flashInstructions": "Flashing only works if the SD card slot on the Manta is empty.",
	"documentationLink": "https://os.ratrig.com/docs/boards/btt/manta-m5p"
}

=== Rat-OS/RatOS-configuration/boards/btt-ebb42-10/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"name": "BTT-EBB42-10",
	"manufacturer": "BigTreeTech",
	"serialPath": "/dev/btt-ebb42-10",
	"firmwareBinaryName": "firmware-btt-ebb42-10.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"flashInstructions": "",
	"documentationLink": "https://os.ratrig.com/docs/boards/btt/ebb42-10"
}

=== Rat-OS/RatOS-configuration/boards/btt-octopus-pro-h723/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"name": "Octopus Pro H723",
	"manufacturer": "BIGTREETECH",
	"serialPath": "/dev/btt-octopus-pro-h723",
	"firmwareBinaryName": "firmware-btt-octopus-pro-h723.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"flashInstructions": "Flashing only works if the SD card slot on the Octopus Pro is empty.",
	"documentationLink": "https://os.ratrig.com/docs/boards/btt/octopus-pro-h723"
}

=== Rat-OS/RatOS-configuration/boards/fysetc-cheetah-v2/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"name": "Cheetah v2",
	"manufacturer": "Fysetc",
	"serialPath": "/dev/fysetc-cheetah-v2",
	"firmwareBinaryName": "firmware-fysetc-cheetah-v2.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"documentationLink": "https://os.ratrig.com/docs/boards/fysetc/cheetah-v2"
}

=== Rat-OS/RatOS-configuration/boards/btt-octopus-11-407/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"name": "Octopus V1.1 F407",
	"manufacturer": "BIGTREETECH",
	"serialPath": "/dev/btt-octopus-11-407",
	"firmwareBinaryName": "firmware-btt-octopus-11-407.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"flashInstructions": "Flashing only works if the SD card slot on the Octopus is empty.",
	"documentationLink": "https://os.ratrig.com/docs/boards/btt/octopus-11-407"
}

=== Rat-OS/RatOS-configuration/boards/btt-manta-m8p/board-definition.json
{
	"$schema": "../board-definition.schema.json",
	"name": "Manta M8P",
	"manufacturer": "BIGTREETECH",
	"serialPath": "/dev/btt-manta-m8p",
	"firmwareBinaryName": "firmware-btt-manta-m8p.bin",
	"compileScript": "compile.sh",
	"flashScript": "flash.sh",
	"documentationLink": "https://os.ratrig.com/docs/boards/btt/manta-m8p"
}
